name: Fetch Data
on:
  schedule:
    - cron: 0 0 * * *
  workflow_dispatch: {}
  push:
    paths:
      - .github/workflows/data.yml
jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
      - name: Setup deno
        uses: denoland/setup-deno@main
        with:
          deno-version: v1.x

      - name: Setup dart
        uses: dart-lang/setup-dart@v1

      - name: Check out repo
        uses: actions/checkout@v2

      - name: Pub get
        run: dart pub get

      - name: Start API
        run: dart run bin/server.dart & dart --version

      - name: Cache Requests
        uses: githubocto/flat@v3
        with:
          http_url: http://localhost:8080/cache
          downloaded_filename: cache.json

      - name: Fetch data
        uses: githubocto/flat@v3
        with:
          http_url: https://storage.googleapis.com/flutter_infra_release/releases/releases_macos.json
          downloaded_filename: releases-macos.json
      - name: Fetch data
        uses: githubocto/flat@v3
        with:
          http_url: https://storage.googleapis.com/flutter_infra_release/releases/releases_windows.json
          downloaded_filename: releases-windows.json
      - name: Fetch data
        uses: githubocto/flat@v3
        with:
          http_url: https://storage.googleapis.com/flutter_infra_release/releases/releases_linux.json
          downloaded_filename: releases-linux.json

      - name: Flutter Favorites
        uses: githubocto/flat@v3
        with:
          http_url: http://localhost:8080/flutter-favorites
          downloaded_filename: flutter-favorites.json

      - name: Google Packages
        uses: githubocto/flat@v3
        with:
          http_url: http://localhost:8080/google-packages
          downloaded_filename: google-packages.json

      - name: Fetch Trending Today
        uses: githubocto/flat@v3
        with:
          http_url: http://localhost:8080/trending/today
          downloaded_filename: trending-repository-today.json

      - name: Fetch Trending Week
        uses: githubocto/flat@v3
        with:
          http_url: http://localhost:8080/trending/week
          downloaded_filename: trending-repository-week.json

      - name: Fetch Trending Month
        uses: githubocto/flat@v3
        with:
          http_url: http://localhost:8080/trending/month
          downloaded_filename: trending-repository-month.json

      - name: Most Popular Packages
        uses: githubocto/flat@v3
        with:
          http_url: http://localhost:8080/packages/most-popular
          downloaded_filename: packages-most-popular.json

      - name: Most Liked Packages
        uses: githubocto/flat@v3
        with:
          http_url: http://localhost:8080/packages/most-liked
          downloaded_filename: packages-most-liked.json

      - name: Recently Updated Packages
        uses: githubocto/flat@v3
        with:
          http_url: http://localhost:8080/packages/recently-updated
          downloaded_filename: packages-recently-updated.json

      - name: Recently Created Packages
        uses: githubocto/flat@v3
        with:
          http_url: http://localhost:8080/packages/recently-created
          downloaded_filename: packages-recently-created.json
